---
- name: Deploy API Health Checker
  hosts: ec2
  become: yes
  vars:
    image: harshit0400/api-health-checker:latest
    container_name: api-health-checker
    app_port: 5001

  tasks:
    - name: Install Docker
      apt:
        name: docker.io
        state: present
        update_cache: yes

    - name: Start and enable Docker
      service:
        name: docker
        state: started
        enabled: yes

    - name: Pull latest Docker image
      shell: docker pull {{ image }}

    - name: Stop existing container if running
      shell: docker stop {{ container_name }}
      ignore_errors: yes

    - name: Remove existing container if exists
      shell: docker rm {{ container_name }}
      ignore_errors: yes

    - name: Run new container
      shell: >
        docker run -d
        --name {{ container_name }}
        --restart unless-stopped
        -p {{ app_port }}:{{ app_port }}
        -e AWS_ACCESS_KEY_ID="{{ lookup('env', 'AWS_ACCESS_KEY_ID') }}"
        -e AWS_SECRET_ACCESS_KEY="{{ lookup('env', 'AWS_SECRET_ACCESS_KEY') }}"
        -e AWS_REGION="{{ lookup('env', 'AWS_REGION') }}"
        {{ image }}

    - name: Confirm container is running
      shell: docker ps | grep {{ container_name }}
      register: result

    - name: Print container status
      debug:
        msg: "{{ result.stdout }}"